const express = require("express");
const router = express.Router();

const categoria_productosRoutes = require("./categoria_productosRoutes");
const clienteRoutes = require("./clienteRoutes");
const clientesRoutes = require("./clientesRoutes");
const compraRoutes = require("./comprasRoutes");
const cronogramasRoutes = require("./cronogramasRoutes");
const detalle_compraRoutes = require("./detalle_compraRoutes");
const detalle_permisoRoutes = require("./detalle_permisoRoutes");
const estado_ventaRoutes = require("./estado_ventaRoutes");
const pedidosRoutes = require("./pedidosRoutes");
const permisosRoutes = require("./permisosRoutes");
const productosRoutes = require("./productosRoutes");
const proveedorRoutes = require("./proveedorRoutes");
const rolesRoutes = require("./rolesRoutes");
const rutasRoutes = require("./rutasRoutes");
const testRoutes = require("./testRoutes");
const usuariosRoutes = require("./usuariosRoutes");
const ventaRoutes = require("./ventaRoutes");
const zonasRoutes = require("./zonasRoutes");

router.use("/categoria_productos", categoria_productosRoutes);
router.use("/cliente", clienteRoutes);
router.use("/clientes", clientesRoutes);
router.use("/compras", compraRoutes);
router.use("/cronogramas", cronogramasRoutes);
router.use("/detalle_compra", detalle_compraRoutes);
router.use("/detalle_permiso", detalle_permisoRoutes);
router.use("/estado_venta", estado_ventaRoutes);
router.use("/pedidos", pedidosRoutes);
router.use("/permisos", permisosRoutes);
router.use("/productos", productosRoutes);
router.use("/proveedores", proveedorRoutes);
router.use("/roles", rolesRoutes);
router.use("/rutas", rutasRoutes);
router.use("/test", testRoutes);
router.use("/usuarios", usuariosRoutes);
router.use("/ventas", ventaRoutes);
router.use("/zonas", zonasRoutes);

module.exports = router;
